### ISSUE TITLE
docker build baseimage failed

### ISSUE THREAD

**Issue by ronnywang** [g0v/api.ly#73]
```
> ./docker/baseimage/scripts/build-image.sh
Step 12 : RUN chef-solo -c /chef/solo.rb -j /chef/solo.json
 ---> Running in f076826c3c53
[2016-08-30T06:55:47+00:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at /ch
ef
  One version per cookbook

[2016-08-30T06:55:47+00:00] INFO: Forking chef instance to converge...
[2016-08-30T06:55:47+00:00] INFO: *** Chef 12.13.37 ***
[2016-08-30T06:55:47+00:00] INFO: Platform: x86_64-linux
[2016-08-30T06:55:47+00:00] INFO: Chef-client pid: 13
[2016-08-30T06:55:51+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/nodes/95699cec7d3e
[2016-08-30T06:55:51+00:00] INFO: Setting the run_list to ["recipe[ly.g0v.tw]"] from CLI options
[2016-08-30T06:55:51+00:00] INFO: Run List is [recipe[ly.g0v.tw]]
[2016-08-30T06:55:51+00:00] INFO: Run List expands to [ly.g0v.tw]
[2016-08-30T06:55:51+00:00] INFO: Starting Chef Run for 95699cec7d3e
[2016-08-30T06:55:51+00:00] INFO: Running start handlers
[2016-08-30T06:55:51+00:00] INFO: Start handlers complete.
[2016-08-30T06:55:51+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found:
[2016-08-30T06:55:51+00:00] INFO: Loading cookbooks [ly.g0v.tw@0.1.0, postgresql@0.16.1, apt@4.0.2, compat_resource@12.14.0]

================================================================================
Error Syncing Cookbooks:
================================================================================

Unexpected Error:
-----------------
NoMethodError: private method `select' called for nil:NilClass

Platform:
---------
x86_64-linux

[2016-08-30T06:55:51+00:00] ERROR: Running exception handlers
[2016-08-30T06:55:51+00:00] ERROR: Exception handlers complete
[2016-08-30T06:55:51+00:00] FATAL: Stacktrace dumped to /chef/chef-stacktrace.out
[2016-08-30T06:55:51+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-08-30T06:55:51+00:00] ERROR: private method `select' called for nil:NilClass
[2016-08-30T06:55:53+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
The command '/bin/sh -c chef-solo -c /chef/solo.rb -j /chef/solo.json' returned a non-zero code: 1
```

```
root@68fb1ccbdb55:/# cat /chef/chef-stacktrace.out
Generated at 2016-08-30 06:58:32 +0000
NoMethodError: private method `select' called for nil:NilClass
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/cookbook/synchronizer.rb:205:in `block in remove_deleted_files'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/cookbook/synchronizer.rb:199:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/cookbook/synchronizer.rb:199:in `remove_deleted_files'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/cookbook/synchronizer.rb:226:in `clear_obsoleted_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/cookbook/synchronizer.rb:147:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/policy_builder/expand_node_object.rb:223:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/policy_builder/expand_node_object.rb:83:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/client.rb:510:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/client.rb:280:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:302:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:290:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:290:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:255:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:243:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/solo.rb:226:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:53:in `load'
/usr/bin/chef-solo:53:in `<main>'
```

**Comment by ronnywang** [comment]
看 /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/cookbook/synchronizer.rb 的程式碼
好像死在 cookbook_segment(cookbook_name, segment) 回傳了 nil
而死掉時的 cookbook_name 是 postgresql, segment 是 config
